kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: api-backoffice
spec:
  replicas: 1
  template:
    metadata:
      name: api-backoffice
      labels:
        app: api-backoffice
        role: backend
        env: production
    spec:
      containers:
      - name: api-backoffice
        image: gcr.io/turing-audio-227423/api-backoffice:v25
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        # command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080
