apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: JOB_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: JOB_NAME
    spec:
      containers:
      - name: JOB_NAME
        image: gcr.io/turing-audio-227423/JOB_NAME:vBUILD_NUMBER
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        ports:
          - containerPort: 9007
